language: java
jdk:
  - oraclejdk8
install:
  - true
before_install:
  - nvm install 5.0
  - nvm use 5.0
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
#  - cd www/
#  - npm install
#  - npm run gulp
#  - npm test
#  - cd ../
cache:
  directories:
    - $HOME/.gradle/cache
    - www/node_modules
:
script: gradle build --info
