sudo: required
language: java
before_install:
  - curl --silent --location https://deb.nodesource.com/setup_0.12 | sudo bash -
  - sudo apt-get install --yes nodejs build-essential nodejs-legacy
  - chmod +x www/build.sh
script: "./gradlew build"
jdk:
  - oraclejdk8
