language: java
jdk: openjdk8
node_js: "5.1"
cache:
  directories:
    - $HOME/.gradle
    - ./node_modules
install:
  - true
before_install:
# - nvm install 5.1
# - nvm use 5.1
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - ./gradlew www -Pnode=dev
  - ./gradlew build
notifications:
  email: false
