sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
  - openjdk8
cache:
  directories:
    - $HOME/.gradle/caches
    - www/node_modules
install:
  - true
before_install:
  - nvm install 5.1
  - nvm use 5.1
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - gradle build
notifications:
  email:
    recipients:
      - daggerok@gmail.com
    on_failure: change # always
    on_success: never

