language: java
jdk:
  - oraclejdk8
before_script:
  - nvm install 5.0
  - nvm use 5.0
  - export DISPLAY=:99.0 
  - sh -e /etc/init.d/xvfb start
script:
  - gradle build
after_script:
  - cd www
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm test

