app.zip.mimes: >
  application/json,application/javascript,application/x-woff,application/xml,
  application/xhtml+xml,application/xml-dtd,application/atom+xml,
  image/gif,image/png,image/jpeg,image/pjpeg,image/svg+xml,
  message/http,message/imdn+xml,message/partial,message/rfc822,
  text/plain,text/css,text/html,text/json,text/xml,text/cmd,text/csv
application:
  name: blog
server:
  port: 8080
  tomcat:
    compression: 512
    compressable-mime-types: ${app.zip.mimes}
http:
  gzip:
    deflate-compression-level: 5
    methods: GET,POST,PUT,DELETE
    mime-types: ${app.zip.mimes}
    min-gzip-size: 512
management:
  context-path: /admin
  address: 127.0.0.1
  port: 8081
endpoints:
  sensitive: false
  enabled: true
  shutdown:
    sensitive: false
    enabled: true
  health:
    time-to-live: 60000
spring:
  profiles.active: dev
  data:
    rest:
      base-path: /api
      base-uri: /api
    mongodb:
      port: 0
  datasource:
    driver-class-name: com.mongodb.Mongo
    name: ${application.name}
    username: ${application.name}
    password: ${application.name}
---
spring:
  profiles: prod
logging:
  level:
    root: INFO
---
spring:
  profiles: dev
security:
  basic:
    enabled: false
logging:
  level:
    root: INFO